roles: []
settings:
  api_port: 5000
  auto_clear_idle_sec: 0
  auto_overlay_on_send: true
  auto_overlay_out_on_clear: true
  clear_on_blank: true
  max_chars_per_line: 48
  openlp_ws_url: ws://localhost:4317
  overlay_always_on: false
  overlay_channel: 1
  poll_interval_sec: 2
  splash_enabled: true
  vmix_api_url: http://localhost:8088/api
  vmix_title_field: Message.Text
  vmix_title_input: SongTitle
ui:
  theme: darkly
