name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    env:
      APP_DIR: lyrisync_plus

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Confirm repo layout
        run: |
          Write-Host "PWD: $(Get-Location)"
          Get-ChildItem -Force
          Write-Host "Contents of $env:APP_DIR:"
          if (!(Test-Path "$env:APP_DIR")) { throw "App directory '$env:APP_DIR' not found." }
          Get-ChildItem -Force "$env:APP_DIR"

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: ${{ env.APP_DIR }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Show installed packages (debug)
        working-directory: ${{ env.APP_DIR }}
        run: |
          python -c "import pkgutil; print(sorted([m.name for m in pkgutil.iter_modules()]))"
          python -c "import aiohttp, websockets, yaml, PIL; print('OK: aiohttp, websockets, yaml, PIL')"

      - name: Build executable via spec
        working-directory: ${{ env.APP_DIR }}
        run: |
          if (!(Test-Path "LyriSyncPlus.spec")) { throw "Missing LyriSyncPlus.spec in $env:APP_DIR" }
          pyinstaller LyriSyncPlus.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LyriSyncPlus-exe
          path: ${{ env.APP_DIR }}/dist/LyriSyncPlus/LyriSyncPlus.exe
