name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: lyricsyn_plus
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        working-directory: lyricsyn_plus
        run: |
          pyinstaller --noconsole --onefile main.py -n LyriSyncPlus `
            --add-data "splash.png;." `
            --hidden-import ttkbootstrap `
            --hidden-import websockets `
            --hidden-import aiohttp `
            --hidden-import yaml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LyriSyncPlus-exe
          path: lyricsyn_plus/dist/LyriSyncPlus.exe
